# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-12 08:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strongholdcoins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=10, unique=True)),
                ('wallet_address', models.CharField(max_length=255)),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('order_status', models.CharField(choices=[('P', 'Pending'), ('AW', 'Awaiting Payment'), ('AP', 'Approved'), ('W', 'With Held')], default='P', max_length=1)),
                ('action', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell'), ('I', 'Invest')], default='B', max_length=1)),
                ('payment_method', models.CharField(blank=True, choices=[('AMM', 'Mobile Money'), ('BAT', 'Bank Account Transfer')], default='AMM', max_length=3)),
                ('mobile_money_vendor', models.CharField(blank=True, choices=[('MTN', 'MTN'), ('VODAFONE', 'VODAFONE'), ('AIRTEL', 'AIRTEL'), ('TIGO', 'TIGO')], default='MTN', max_length=10, null=True)),
                ('mobile_money_number', models.CharField(blank=True, max_length=10, null=True)),
                ('bank', models.CharField(blank=True, choices=[('', 'Select Bank'), ('GT', 'GT BANK'), ('ZB', 'ZENITH BANK'), ('SB', 'STANBIC BANK'), ('EB', 'ECOBANK'), ('UB', 'UNIBANK'), ('CB', 'CAL BANK')], max_length=2, null=True)),
                ('bank_account_name', models.CharField(blank=True, max_length=105, null=True)),
                ('bank_account_number', models.BigIntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='birthdate',
            new_name='birth_date',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
