# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-13 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0003_auto_20170912_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('P', 'Pending'), ('AW', 'Awaiting Payment'), ('AP', 'Approved'), ('W', 'With Held')], default='AW', max_length=2),
        ),
    ]
