# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-14 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0012_auto_20170914_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='other_names',
        ),
    ]
