# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-14 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0013_remove_userprofile_other_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='btc_amount',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='dollar_rate',
        ),
    ]
