# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-14 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0014_auto_20170914_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='action',
            field=models.CharField(blank=True, choices=[('B', 'Buy'), ('S', 'Sell'), ('I', 'Invest')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='rate',
            name='btc_amount',
            field=models.DecimalField(decimal_places=2, max_digits=99999, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='dollar_per_btc',
            field=models.DecimalField(decimal_places=2, max_digits=99999, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='tax_fee',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='transaction_fee',
            field=models.DecimalField(decimal_places=2, max_digits=100, null=True),
        ),
    ]
