# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-18 11:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0016_auto_20170916_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='identity_card',
            field=models.FileField(blank=True, null=True, upload_to='identity_folder'),
        ),
    ]
