# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-18 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0017_userprofile_identity_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identity_card',
            field=models.FileField(blank=True, null=True, upload_to='identity_folder/'),
        ),
    ]
