# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-09-19 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0020_rate_cryptocurrency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cryptocurrency',
            field=models.CharField(blank=True, choices=[('BITCOIN', 'BITCOIN'), ('ETHIRIUM', 'ETHIRIUM'), ('LITHIUM', 'LITHIUM')], default='BITCOIN', max_length=12),
        ),
    ]
