# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-03 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0021_order_cryptocurrency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='btc_amount',
        ),
        migrations.RemoveField(
            model_name='rate',
            name='dollar_per_btc',
        ),
    ]
