# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-04 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0023_remove_rate_cryptocurrency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='mobile_money_vendor',
            field=models.CharField(blank=True, choices=[('', 'Select Vendor'), ('MTN', 'MTN'), ('VODAFONE', 'VODAFONE'), ('AIRTEL', 'AIRTEL'), ('TIGO', 'TIGO')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Select Method'), ('AMM', 'Mobile Money'), ('BAT', 'Bank Account Transfer')], default='', max_length=4),
        ),
    ]
