# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-07 08:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0024_auto_20171004_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cryptocurrency',
            field=models.CharField(blank=True, choices=[('BITCOIN', 'BITCOIN'), ('ETHERIUM', 'ETHERIUM'), ('LITECOIN', 'LITECOIN')], default='BITCOIN', max_length=12),
        ),
    ]
