# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-07 09:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0025_auto_20171007_0856'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_of_coins',
            field=models.DecimalField(decimal_places=2, max_digits=99999, null=True),
            preserve_default=False,
        ),
    ]
