# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-07 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0026_order_amount_of_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_of_coins',
        ),
    ]
