# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-08 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0027_remove_order_amount_of_coins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='cryptocurrency',
            new_name='crypto_currency',
        ),
    ]
