# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-08 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0028_auto_20171008_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_of_coins',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=99999),
        ),
    ]
