# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-08 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0030_auto_20171008_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank',
            field=models.CharField(blank=True, choices=[('GT Bank', 'GT BANK'), ('Zenith Bank', 'ZENITH BANK'), ('Stanbic Bank', 'STANBIC BANK'), ('EcoBank', 'ECOBANK'), ('UniBank', 'UNIBANK'), ('Cal Bank', 'CAL BANK')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='mobile_money_vendor',
            field=models.CharField(blank=True, choices=[('MTN', 'MTN'), ('VODAFONE', 'VODAFONE'), ('AIRTEL', 'AIRTEL'), ('TIGO', 'TIGO')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('', 'Select Method'), ('AMM', 'Mobile Money'), ('BAT', 'Bank Account Transfer')], max_length=4),
        ),
    ]
