# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-08 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0031_auto_20171008_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('AMM', 'Mobile Money'), ('BAT', 'Bank Account Transfer')], max_length=4),
        ),
    ]
