# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-09 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0032_auto_20171008_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
