# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-09 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0034_auto_20171009_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
