# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-09 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0036_auto_20171009_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='crypto_currency',
            field=models.CharField(blank=True, choices=[('Bitcoin', 'Bitcoin'), ('Ethereum', 'Ethereum'), ('Ethereum', 'Litecoin')], default='Bitcoin', max_length=12),
        ),
    ]
