# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-11 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0039_auto_20171010_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_fee',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=99999),
        ),
    ]
