# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-12 10:12
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0040_order_commission_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identity_card',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identity_card', to='filer.File'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='filer.Image'),
        ),
    ]
