# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-10-12 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strongholdcoins', '0041_auto_20171012_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='identity_card',
            field=models.FileField(blank=True, null=True, upload_to='identity_folder/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
